# Generated by Django 4.2.3 on 2023-08-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recursos_link_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='usuario_curso',
            field=models.ManyToManyField(to='main.usuarios'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='usuario_evento',
            field=models.ManyToManyField(to='main.usuarios'),
        ),
        migrations.AddField(
            model_name='roles',
            name='usuario_rol',
            field=models.ManyToManyField(to='main.usuarios'),
        ),
    ]
